#!/bin/sh

VERS=$(nvram get webs_state_info)

. /jffs/scripts/credentials.sh

push_message () {
	echo "Pushover Init"
	curl -s \
		 --form-string "token=$pushover_token" \
		 --form-string "user=$pushover_user" \
		 --form-string "message=Firmware Update: $VERS" \
		https://api.pushover.net/1/messages.json
}
push_message
